'use client';
import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Plus,Trash2,ArrowUp,Save,Image as ImageIcon} from 'lucide-react';
import {SiteContent} from '@/lib/content';
import {Field,PhotoUpload,Choice,api} from '../shared';
import {toast} from 'sonner';
export default function Editor({site,revision,reload}:{site:SiteContent;revision:number;reload:()=>Promise<void>}){
 const [draft,setDraft]=useState<SiteContent>(structuredClone(site)),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const set=(key:keyof SiteContent,value:any)=>{setDraft(d=>({...d,[key]:value}));setDirty(true);};
 const text=(key:keyof SiteContent,label:string,multi=false,hint='')=><Field label={label} hint={hint}>{multi?<textarea rows={4} value={String(draft[key])} onChange={e=>set(key,e.target.value)}/>:<input value={String(draft[key])} onChange={e=>set(key,e.target.value)}/>}</Field>;
 async function save(){setBusy(true);try{await api({action:'save-content',data:draft,revision});await reload();setDirty(false);toast.success('Site atualizado. As mudanças já estão disponíveis.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 return <div className="content-editor"><div className="editor-toolbar"><div><h2>O site, do seu jeito.</h2><p>{dirty?'Há alterações ainda não salvas.':'Altere textos, fotos e informações da escolinha.'}</p></div><button className="btn btn-yellow" onClick={save} disabled={busy||!dirty}><Save size={17}/>{busy?'Salvando...':'Salvar alterações'}</button></div><Tabs defaultValue="home"><TabsList className="editor-tabs"><TabsTrigger value="home">Início</TabsTrigger><TabsTrigger value="school">Escolinha</TabsTrigger><TabsTrigger value="team">Professores</TabsTrigger><TabsTrigger value="photos">Galeria</TabsTrigger><TabsTrigger value="contact">Contato e dúvidas</TabsTrigger></TabsList>
 <TabsContent value="home"><section className="admin-card edit-section"><h3>Identidade e primeira impressão</h3><div className="form-grid">{text('name','Nome da escolinha')}{text('tagline','Linha de apresentação')}</div><PhotoUpload value={draft.logo} onChange={v=>set('logo',v)} label="Alterar logo" hint="Recomendado: 600 × 600 px • proporção 1:1 • até 5 MB"/>{text('heroTitle','Título principal',true,'Use uma quebra de linha para destacar a segunda frase em amarelo.')}{text('heroText','Texto de apresentação',true)}{text('heroCta','Texto do botão')}</section><section className="admin-card edit-section"><div className="row-between"><h3>Slides da capa</h3><button className="btn btn-outline btn-small" onClick={()=>set('slides',[...draft.slides,{src:draft.slides[0].src,alt:'Nova foto da escolinha',label:'MÉIER FUTSAL',position:'center'}])}><Plus size={16}/>Adicionar slide</button></div><p className="muted">Recomendado: 1920 × 1080 px (16:9). Prefira fotos com a ação no lado direito.</p>{draft.slides.map((s,i)=><div className="edit-row" key={i}><div className="row-between"><h4>Slide {i+1}</h4><div className="row-actions"><button className="icon-btn" title="Mover para cima" disabled={i===0} onClick={()=>{const a=[...draft.slides];[a[i-1],a[i]]=[a[i],a[i-1]];set('slides',a);}}><ArrowUp size={16}/></button><button className="icon-btn danger-text" title="Remover slide" disabled={draft.slides.length===1} onClick={()=>set('slides',draft.slides.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div></div><PhotoUpload value={s.src} onChange={v=>set('slides',draft.slides.map((x,j)=>j===i?{...x,src:v}:x))}/><div className="form-grid"><Field label="Descrição da foto"><input value={s.alt} onChange={e=>set('slides',draft.slides.map((x,j)=>j===i?{...x,alt:e.target.value}:x))}/></Field><Field label="Legenda do slide"><input value={s.label} onChange={e=>set('slides',draft.slides.map((x,j)=>j===i?{...x,label:e.target.value}:x))}/></Field></div><Field label="Enquadramento"><Choice value={s.position} onChange={v=>set('slides',draft.slides.map((x,j)=>j===i?{...x,position:v}:x))} options={[{value:'center',label:'Centralizado'},{value:'top',label:'Priorizar parte superior'},{value:'bottom',label:'Priorizar parte inferior'}]}/></Field></div>)}</section></TabsContent>
 <TabsContent value="school"><section className="admin-card edit-section"><h3>História e propósito</h3><div className="form-grid">{text('aboutEyebrow','Chamada da seção')}{text('founded','Ano de fundação',false,'Deixe vazio até confirmar o ano.')}</div>{text('aboutTitle','Título',true)}{text('aboutText','Apresentação da escolinha',true)}{text('history','Nossa história',true)}<PhotoUpload value={draft.aboutImage} onChange={v=>set('aboutImage',v)} label="Trocar foto da escolinha" hint="Recomendado: 1200 × 1000 px • proporção 6:5 • até 5 MB"/></section><section className="admin-card edit-section"><h3>Nossos valores</h3>{draft.values.map((v,i)=><div className="form-grid" key={i}><Field label={'Valor '+(i+1)}><input value={v.title} onChange={e=>set('values',draft.values.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/></Field><Field label="Descrição"><textarea rows={3} value={v.text} onChange={e=>set('values',draft.values.map((x,j)=>j===i?{...x,text:e.target.value}:x))}/></Field></div>)}</section></TabsContent>
 <TabsContent value="team"><section className="admin-card edit-section">{text('teamTitle','Título da seção',true)}{text('teamText','Apresentação da equipe',true)}<div className="notice">As fotos e os nomes enviados já estão aqui. Complete a formação, a trajetória e o tempo de equipe com as informações de cada professor.</div></section>{draft.coaches.map((c,i)=>{const change=(key:string,value:string)=>set('coaches',draft.coaches.map((x,j)=>j===i?{...x,[key]:value}:x));return <section className="admin-card edit-section" key={c.id}><div className="row-between"><h3>{c.name}</h3><button className="icon-btn danger-text" title="Remover professor da página" onClick={()=>set('coaches',draft.coaches.filter((_,j)=>j!==i))}><Trash2 size={17}/></button></div><div className="form-grid"><Field label="Nome"><input value={c.name} onChange={e=>change('name',e.target.value)}/></Field><Field label="Função"><input value={c.role} onChange={e=>change('role',e.target.value)}/></Field></div><PhotoUpload value={c.image} label="Enviar retrato individual" hint="Recomendado: 800 × 1000 px • proporção 4:5 • até 5 MB" onChange={v=>set('coaches',draft.coaches.map((x,j)=>j===i?{...x,image:v,crop:''}:x))}/><Field label="Biografia completa"><textarea rows={4} value={c.bio} onChange={e=>change('bio',e.target.value)}/></Field><div className="form-grid"><Field label="Formação e experiência"><textarea rows={3} value={c.qualifications} onChange={e=>change('qualifications',e.target.value)}/></Field><Field label="Na equipe desde"><input value={c.since} placeholder="Ex.: 2020" onChange={e=>change('since',e.target.value)}/></Field></div></section>;})}<button className="btn btn-outline" onClick={()=>set('coaches',[...draft.coaches,{id:crypto.randomUUID(),name:'Novo professor',role:'Professor',bio:'',qualifications:'',since:'',image:draft.logo,crop:''}])}><Plus size={17}/>Adicionar professor</button></TabsContent>
 <TabsContent value="photos"><section className="admin-card edit-section">{text('galleryTitle','Título da galeria',true)}<p className="muted">Fotos recomendadas: 1200 × 1200 px ou 1200 × 900 px. JPG, PNG ou WebP de até 5 MB.</p><div className="gallery-editor">{draft.gallery.map((g,i)=><div className="edit-row" key={i}><PhotoUpload value={g.src} onChange={v=>set('gallery',draft.gallery.map((x,j)=>j===i?{...x,src:v}:x))}/><Field label="Descrição da foto"><input value={g.alt} onChange={e=>set('gallery',draft.gallery.map((x,j)=>j===i?{...x,alt:e.target.value}:x))}/></Field><Field label="Legenda"><input value={g.label} onChange={e=>set('gallery',draft.gallery.map((x,j)=>j===i?{...x,label:e.target.value}:x))}/></Field><div className="row-actions"><button className="btn btn-outline btn-small" disabled={!i} onClick={()=>{const a=[...draft.gallery];[a[i-1],a[i]]=[a[i],a[i-1]];set('gallery',a);}}><ArrowUp size={15}/>Subir</button><button className="btn btn-outline btn-small danger-text" onClick={()=>set('gallery',draft.gallery.filter((_,j)=>j!==i))}><Trash2 size={15}/>Remover</button></div></div>)}</div><button className="btn btn-outline" onClick={()=>set('gallery',[...draft.gallery,{src:draft.aboutImage,alt:'Momento em quadra',label:'MÉIER FUTSAL'}])}><Plus size={17}/>Adicionar foto</button></section></TabsContent>
 <TabsContent value="contact"><section className="admin-card edit-section"><h3>Visitas e contato</h3>{text('visitTitle','Título do convite',true)}{text('visitText','Texto do convite',true)}<div className="form-grid">{text('location','Nome do local')}{text('address','Endereço')}{text('city','Bairro, cidade e estado')}{text('whatsapp','WhatsApp',false,'Com código do país e DDD: 5521...')}{text('email','E-mail da escolinha')}{text('instagram','Link do Instagram')}</div>{text('reviewsTitle','Título das avaliações',true)}</section><section className="admin-card edit-section"><div className="row-between"><h3>Perguntas frequentes</h3><button className="btn btn-outline btn-small" onClick={()=>set('faq',[...draft.faq,{q:'Nova pergunta',a:''}])}><Plus size={16}/>Adicionar</button></div>{draft.faq.map((f,i)=><div className="edit-row" key={i}><div className="row-between"><strong>Pergunta {i+1}</strong><button className="icon-btn danger-text" title="Remover pergunta" onClick={()=>set('faq',draft.faq.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div><Field label="Pergunta"><input value={f.q} onChange={e=>set('faq',draft.faq.map((x,j)=>j===i?{...x,q:e.target.value}:x))}/></Field><Field label="Resposta"><textarea rows={3} value={f.a} onChange={e=>set('faq',draft.faq.map((x,j)=>j===i?{...x,a:e.target.value}:x))}/></Field></div>)}</section></TabsContent>
 </Tabs><div className="editor-footer"><span>{dirty?'Alterações não salvas':'Tudo salvo'}</span><button className="btn btn-yellow" disabled={busy||!dirty} onClick={save}><Save size={16}/>Salvar alterações</button></div></div>;
}
