'use client';
import {useState} from 'react';
import {LockKeyhole,Mail,ShieldCheck,LoaderCircle,ArrowRight} from 'lucide-react';
import {toast,Toaster} from 'sonner';
import './admin.css';

export default function AdminLogin({configured}:{configured:boolean}){
 const [mode,setMode]=useState(configured?'login':'setup'),[busy,setBusy]=useState(false),[form,setForm]=useState({name:'',email:'',password:'',confirm:''});
 const patch=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 async function submit(e:React.FormEvent){e.preventDefault();if(mode==='setup'&&form.password!==form.confirm){toast.error('As senhas não coincidem.');return;}setBusy(true);try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,email:form.email,name:form.name,password:form.password})});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível entrar.');location.href='/admin';}catch(err){toast.error((err as Error).message);}finally{setBusy(false);}}
 return <main className="admin-login-page"><Toaster richColors position="top-right"/><div className="admin-login-shell"><section className="admin-login-brand"><img src="/images/logo.jpeg" alt="Méier Futsal"/><span>PAINEL DE GESTÃO</span><h1>Controle a escolinha sem complicação.</h1><p>Alunos, mensalidades, turmas, presença, visitas, inscrições, avaliações e conteúdo do site em um só lugar.</p><div className="login-feature"><ShieldCheck size={20}/><div><strong>Administração privada</strong><small>Seu acesso fica protegido por senha e sessão segura.</small></div></div></section><section className="admin-login-card"><div className="login-icon"><LockKeyhole size={24}/></div><p className="mini-label">MÉIER FUTSAL / ADMIN</p><h2>{mode==='setup'?'Criar acesso administrador':'Entrar no painel'}</h2><p className="login-help">{mode==='setup'?'Primeiro acesso: escolha o e-mail e a senha que serão usados para administrar o site.':'Use o acesso administrativo configurado para a escolinha.'}</p><form onSubmit={submit} className="login-form">{mode==='setup'&&<label><span>Seu nome</span><input autoFocus required value={form.name} onChange={e=>patch('name',e.target.value)} placeholder="Administrador"/></label>}<label><span>E-mail</span><div className="input-icon"><Mail size={17}/><input type="email" required autoFocus={mode==='login'} value={form.email} onChange={e=>patch('email',e.target.value)} placeholder="seu@email.com"/></div></label><label><span>Senha</span><input type="password" required minLength={8} value={form.password} onChange={e=>patch('password',e.target.value)} placeholder="Mínimo de 8 caracteres"/></label>{mode==='setup'&&<label><span>Confirmar senha</span><input type="password" required minLength={8} value={form.confirm} onChange={e=>patch('confirm',e.target.value)} placeholder="Repita a senha"/></label>}<button className="btn btn-yellow full login-submit" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<>{mode==='setup'?'Criar acesso':'Entrar'}<ArrowRight size={18}/></>}</button></form><a className="login-back" href="/">← Voltar para o site</a></section></div></main>;
}
