'use client';
import {useState} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Upload,LoaderCircle} from 'lucide-react';
import {toast} from 'sonner';
export function Choice({value,onChange,options,placeholder='Selecione',name}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];placeholder?:string;name?:string}){return <Select name={name} value={value||'__none'} onValueChange={v=>onChange(v==='__none'?'':v)}><SelectTrigger className="field-select" aria-label={name||placeholder}><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{!options.some(x=>x.value==='')&&<SelectItem value="__none">{placeholder}</SelectItem>}{options.map(x=><SelectItem key={x.value} value={x.value||'__none'}>{x.label}</SelectItem>)}</SelectContent></Select>;}
export function Tick({checked,onChange,children}:{checked:boolean;onChange:(v:boolean)=>void;children:React.ReactNode}){return <label className="tick"><Checkbox checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{children}</span></label>;}
export function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export async function api(body:any){const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.headers.get('content-type')?.includes('application/json'))throw new Error('Sua sessão expirou. Abra novamente a área administrativa.');const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível salvar.');return d;}
export function PhotoUpload({value,onChange,label='Trocar imagem',hint='JPG, PNG ou WebP • até 5 MB'}:{value:string;onChange:(url:string)=>void;label?:string;hint?:string}){const [busy,setBusy]=useState(false);return <div className="photo-upload">{value&&<img src={value} alt="Imagem selecionada"/>}<div><label className="btn btn-outline btn-small">{busy?<LoaderCircle className="spin" size={16}/>:<Upload size={16}/>} {busy?'Enviando...':label}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5242880){toast.error('A imagem deve ter até 5 MB.');return;}setBusy(true);try{const f=new FormData();f.set('file',file);const r=await fetch('/api/uploads',{method:'POST',body:f});if(!r.headers.get('content-type')?.includes('application/json'))throw new Error('Sua sessão expirou. Abra novamente a área administrativa.');const d:any=await r.json();if(!r.ok)throw new Error(d.error);onChange(d.url);toast.success('Imagem enviada. Salve as alterações para publicar.');}catch(err){toast.error((err as Error).message);}finally{setBusy(false);e.target.value='';}}}/></label><small>{hint}</small></div></div>;}
