import {env} from 'cloudflare:workers';
import {getAdminIdentity} from '@/lib/auth';
import {defaultContent,Item} from './content';
export function bindings(){return env as unknown as {DB:D1Database;BUCKET:R2Bucket};}
export function db(){const d=bindings().DB;if(!d)throw new Error('Serviço de dados indisponível. Tente novamente.');return d;}
export const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export function fail(e:unknown){console.error(e);return reply({error:e instanceof Error?e.message:'Não foi possível concluir. Tente novamente.'},(e as any)?.status||500);}
export function problem(message:string,status=400):never{throw Object.assign(new Error(message),{status});}
export async function admin(){const user=await getAdminIdentity();if(!user)problem('Entre no painel para continuar.',401);return user;}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)problem('Origem não autorizada.',403);if(req.headers.get('sec-fetch-site')==='cross-site')problem('Origem não autorizada.',403);}
export function decode(row:any):Item{return {...row,data:JSON.parse(row.data)};}
export async function all(kind?:string){const r=kind?await db().prepare('SELECT * FROM records WHERE kind=? ORDER BY created_at DESC').bind(kind).all():await db().prepare('SELECT * FROM records ORDER BY created_at DESC').all();return r.results.map(decode);}
export async function get(id:string){const r=await db().prepare('SELECT * FROM records WHERE id=?').bind(id).first();return r?decode(r):null;}
export async function insert(kind:string,data:unknown,id=crypto.randomUUID()){const now=new Date().toISOString();await db().prepare('INSERT INTO records (id,kind,data,revision,created_at,updated_at) VALUES (?,?,?,1,?,?)').bind(id,kind,JSON.stringify(data),now,now).run();return id;}
export async function update(id:string,data:unknown,revision:number){const r=await db().prepare('UPDATE records SET data=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(data),new Date().toISOString(),id,revision).run();if(!r.meta.changes)problem('Este registro mudou. Atualize a página antes de salvar.',409);}
export async function content(){const saved=await get('site_content');return saved?{...defaultContent,...saved.data}:defaultContent;}
export async function rateLimit(req:Request){const ip=req.headers.get('cf-connecting-ip')||'unknown';const date=new Date().toISOString().slice(0,13);const hashed=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ip+date));const key=Array.from(new Uint8Array(hashed)).map(x=>x.toString(16).padStart(2,'0')).join('');const r=await db().prepare('INSERT INTO request_limits (key,count) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key).first<{count:number}>();if(r&&r.count>25)problem('Muitas tentativas. Aguarde antes de enviar novamente.',429);}
export async function saveImage(file:File,visibility='public'){if(file.size>5*1024*1024||file.size===0)problem('Envie uma imagem de até 5 MB.');const bytes=await file.arrayBuffer();const b=new Uint8Array(bytes);let mime='';if(b[0]===255&&b[1]===216&&b[2]===255)mime='image/jpeg';else if(b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71)mime='image/png';else if(String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP')mime='image/webp';if(!mime)problem('Use uma imagem JPG, PNG ou WebP.');const id=crypto.randomUUID();await bindings().BUCKET.put(id,bytes,{httpMetadata:{contentType:mime}});await insert('media',{mime,visibility},id);return '/media/'+id;}
