import {z} from 'zod';
const str=z.string().trim().max(6000);const name=z.string().trim().min(2,'Preencha o nome.').max(140);const phone=z.string().trim().regex(/^[+\d\s().-]{10,22}$/,'Informe um telefone válido com DDD.');
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/,'Informe uma data válida.').refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Data inválida.');
const cents=z.number().int().min(0).max(100000000);const opt=str.optional().default('');
export const studentSchema=z.object({name,birthDate:date,guardian:name,phone,email:z.union([z.literal(''),z.string().email()]).optional().default(''),classId:opt,status:z.enum(['Ativo','Inativo','Experimental']),feeCents:cents,dueDay:z.number().int().min(1).max(28),notes:opt,emergency:opt});
export const classSchema=z.object({name,ages:name,schedule:name,teacher:opt,capacity:z.number().int().min(1).max(500),feeCents:cents,published:z.boolean(),description:opt});
export const expenseSchema=z.object({title:name,amountCents:cents.refine(v=>v>0,'Informe um valor maior que zero.'),date,category:name,paid:z.boolean(),notes:opt});
export const visitSchema=z.object({name,phone,studentName:name,age:z.number().int().min(3).max(99),preferredDate:date,period:z.enum(['Manhã','Tarde','Noite']),message:opt,consent:z.literal(true)});
export const enrollmentSchema=z.object({name,phone,studentName:name,birthDate:date,email:z.union([z.literal(''),z.string().email()]).optional().default(''),classId:opt,message:opt,consent:z.literal(true)});
export const reviewSchema=z.object({name,rating:z.number().int().min(1).max(5),comment:z.string().trim().min(10,'Escreva pelo menos 10 caracteres.').max(1500),consent:z.literal(true)});
export const invoiceSchema=z.object({studentId:name,month:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),amountCents:cents.refine(v=>v>0),dueDate:date});
export const imagePath=z.string().refine(v=>/^\/images\/[a-z0-9.-]+$/.test(v)||/^\/media\/[a-f0-9-]+$/.test(v),'Selecione uma imagem enviada ao site.');
export function parse<T>(schema:z.ZodType<T>,value:unknown):T{const r=schema.safeParse(value);if(!r.success)throw Object.assign(new Error(r.error.issues[0].message),{status:400});return r.data;}
export function validateContent(v:any){const basic=z.object({name,tagline:str,heroTitle:name,heroText:str,heroCta:name,logo:imagePath,slides:z.array(z.object({src:imagePath,alt:name,label:str,position:z.enum(['center','top','bottom'])})).min(1).max(12),aboutEyebrow:str,aboutTitle:name,aboutText:str,history:str,founded:z.string().max(4),aboutImage:imagePath,values:z.array(z.object({title:name,text:str})).max(6),teamTitle:name,teamText:str,coaches:z.array(z.object({id:name,name,role:str,bio:str,qualifications:str,since:str,image:imagePath,crop:z.string().max(20)})).max(30),galleryTitle:name,gallery:z.array(z.object({src:imagePath,alt:name,label:str})).max(40),visitTitle:name,visitText:str,location:str,address:str,city:str,whatsapp:z.string().max(20),email:z.string().max(160),instagram:z.string().url().refine(v=>v.startsWith('https://www.instagram.com/')||v.startsWith('https://instagram.com/')),reviewsTitle:name,faq:z.array(z.object({q:name,a:str})).max(20)});return parse(basic,v);}
